fix: Exclude platform stream version from user stored customized project
quarkusio/code.quarkus.io pull request #1052
Opened 2022-10-07 10:11 UTC by tacsio

fixes #1047

2022-10-07 14:22 UTC, tacsio commented
@ia3andy 
I've finished the PR!

2022-10-14 07:13 UTC, ia3andy requested changes
Mutating the project is a bad idea :)

Bug:
- Select 2.12 and edit project
- Store
- Click on any extension (so that the latest project is set in react state)
- You are back on 2.13 ..

2022-10-18 13:55 UTC, ia3andy approved these changes

2022-10-18 13:55 UTC, ia3andy commented
Thanks!!

2022-10-19 06:58 UTC, merged